frame = "none"

[font]
size = 14
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "FiraCode Nerd Font"

[[font.bold]]
family = "FiraCode Nerd Font"
style = "Bold"

[[font.italic]]
family = "VictorMono Nerd Font Mono"
style = "Italic"

[[font.bold_italic]]
family = "VictorMono Nerd Font Mono"
style = "Bold Italic"
