[window]
padding.x = 16
padding.y = 14
decorations = "none" # Removes the window decoration (title bar, etc.)
startup_mode = "Maximized"
opacity = 0.5
blur = true

[font]
size = 14
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
[colors]
[colors.primary]
background = '0x1e2127'
foreground = '0xffffff'
bright_foreground = '0xe6efff'

[colors.normal]
black = '0x1e2127'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0x828791'

# Bright colors
[colors.bright]
black = '0x5c6370'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0xe6efff'

# Dim colors
[colors.dim]
black = '0x1e2127'
red = '0xe06c75'
green = '0x98c379'
yellow = '0xd19a66'
blue = '0x61afef'
magenta = '0xc678dd'
cyan = '0x56b6c2'
white = '0x828791'


[cursor]
style.shape = "Beam"
style.blinking = "On"
blink_interval = 500
unfocused_hollow = false

[keyboard]
bindings = [
  { key = "Left", mods = "Command", chars = "\u001bOH" },  # Go to start of line
  { key = "Right", mods = "Command", chars = "\u001bOF" }, # Go to end of line
  { key = "Left", mods = "Alt", chars = "\u001bb" },       # Move word left
  { key = "Right", mods = "Alt", chars = "\u001bf" },      # Move word right
  { key = "Back", mods = "Command", chars = "\u0015" },    # Delete line
  { key = "Back", mods = "Alt", chars = "\u001b\u007f" },  # Delete word
]
